### ISSUE TITLE
Update license in README

### ISSUE THREAD

**Issue by mroch** [semgrep/ocaml-tree-sitter-core#61]
https://github.com/returntocorp/ocaml-tree-sitter-core/commit/03ad9c8985bce5efaf2a3b3ced034dc236fc451a changed the license to LGPL but this still refers to GPL3

https://github.com/returntocorp/ocaml-tree-sitter-core/blob/da62d00e5286eed339b8df29f6d4e2289a50b30c/README.md?plain=1#L78-L79

**Comment by aryx** [comment]
Hi @mroch, planning to use ocaml-tree-sitter at facebook? :)

**Comment by mroch** [comment]
no plans yet, but a tree-sitter grammar for flow has come up a few times
